name: Run pytest on PR

on:
  pull_request:
    branches:
      - main  # Adjust branch name as per your setup


jobs:
  test:
    runs-on: ubuntu-latest

    services:
      openobserve:
        image: public.ecr.aws/zinclabs/openobserve:latest

        ports:
          - "5080:5080"
        volumes:
          - data:/data


    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set environment variables1
      env:
        ZO_ROOT_USER_EMAIL: "root@example.com"
        ZO_ROOT_USER_PASSWORD: "Complexpass#123"
        ZO_BASE_URL: http://localhost:5080

      run: |
        echo "export ZO_ROOT_USER_EMAIL=${ZO_ROOT_USER_EMAIL}" >> $GITHUB_ENV
        echo "export ZO_ROOT_USER_PASSWORD=${ZO_ROOT_USER_PASSWORD}" >> $GITHUB_ENV
        echo "export ZO_BASE_URL=${ZO_BASE_URL}" >> $GITHUB_ENV
        echo "Root User Email: $ZO_ROOT_USER_EMAIL"
        echo "Root User Password: $ZO_ROOT_USER_PASSWORD"
        echo "Base URL: $ZO_BASE_URL"

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11.6  # Specify your Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        pip install pytest
        pip install requests

    - name: Run pytest

      run: |
        pytest tests

